# Tuning-options constructor for the counterfactual solver, plus the
# helper that merges user overrides of individual KNITRO options into
# the shipped option files.

#' Control options for the counterfactual solver
#'
#' Constructs the list of tuning options consumed by
#' [tvbounds_counterfactual()]. The defaults reproduce the settings used
#' for the counterfactual application in Palomba (2026).
#'
#' @details
#' The options are stated in the notation of the paper. A candidate
#' distribution \eqn{P}{P} is measured against the baseline
#' \eqn{P_{*}}{P_*} by the divergence
#' \eqn{D_{\phi}(P \| P_{*})}{D_phi(P || P_*)} generated by an entropy
#' function \eqn{\phi}{phi}, and the budget \eqn{\delta}{delta} caps it.
#' At a fixed structural parameter \eqn{\theta}{theta} the inner problem is
#' solved in its dual form, over the multipliers
#' \eqn{(\zeta,\eta,\lambda)}{(zeta, eta, lambda)} attached respectively to
#' the total-mass constraint, to the divergence budget -- so that
#' \eqn{\eta}{eta} is the shadow price of robustness -- and to the moment
#' restrictions. The dual objective integrates against the baseline the
#' perspective of the convex conjugate \eqn{\phi^{*}}{phi^*},
#' \deqn{(\phi^{*})^{\pi}\big(g(U;\theta) - \lambda^{\top} m(U;\theta) -
#'   \zeta, \; \eta\big),}{
#'   (phi^*)^pi( g(U; theta) - lambda' m(U; theta) - zeta,  eta ),}
#' with \eqn{g}{g} the counterfactual criterion and \eqn{m}{m} the moment
#' function. Under total variation,
#' \eqn{\phi_{\mathsf{TV}}(s) = |s-1|/2}{phi_TV(s) = |s - 1| / 2}, the
#' conjugate \eqn{\phi^{*}_{\mathsf{TV}}}{phi_TV^*} is piecewise linear and
#' the perspective collapses to the kinked
#' \eqn{\max\{g(U;\theta) - \lambda^{\top} m(U;\theta) - \zeta, \;
#' -\eta/2\}}{max{g(U; theta) - lambda' m(U; theta) - zeta, -eta/2}}; the
#' smoothing options below round those kinks off, always from above, so the
#' computed bounds stay outward-conservative. The contamination weight
#' \eqn{\kappa}{kappa} of the mixture constraint
#' \eqn{P \geq \kappa P_{*}}{P >= kappa * P_*} is set by `tvmix_kappa`.
#'
#' @param maxsolves Integer, number of multi-start restarts of the outer
#'   optimization over the structural parameter \eqn{\theta}{theta} for each
#'   budget and side.
#' @param startptrange Positive scalar; restarts after the first perturb the
#'   initial \eqn{\theta}{theta} uniformly on
#'   `[-startptrange, startptrange]` coordinate-wise (clipped to the
#'   parameter box).
#' @param use_optim Logical; if `TRUE` the outer optimization uses
#'   Optim.jl (projected L-BFGS with the analytic envelope-theorem
#'   gradient) instead of a nested KNITRO solve. The Optim fallback
#'   avoids nested KNITRO contexts, which segfault with some KNITRO.jl
#'   versions.
#' @param time_limit Positive scalar, wall-clock limit in seconds per outer
#'   Optim run (used only when `use_optim = TRUE`).
#' @param iterations Positive integer, inner iteration limit per outer
#'   Optim run (used only when `use_optim = TRUE`).
#' @param outer_iterations Positive integer, number of Fminbox outer
#'   iterations per Optim run (used only when `use_optim = TRUE`).
#' @param inner_opt Path to a KNITRO option file for the inner (dual)
#'   problem, or `NULL` for the shipped default `inner.opt`.
#' @param outer_opt Path to a KNITRO option file for the outer problem
#'   (over the structural parameter \eqn{\theta}{theta}), or `NULL` for the
#'   shipped default
#'   `outer.opt`. The package also ships `outer_fast.opt` (analytic
#'   envelope gradient, looser tolerances, suited to plotting grids) and
#'   `outer_boot_tv.opt`; point this argument at
#'   `system.file("julia", "opt", "outer_fast.opt", package = "tvbounds")`
#'   to use them.
#' @param knitro_options Named list of individual KNITRO options (e.g.
#'   `list(maxit = 500, outlev = 2)`). These are merged into *both* the
#'   inner and the outer option files by writing merged copies to
#'   [tempdir()]; entries override options already present and are
#'   appended otherwise. Values must be length-one character, numeric, or
#'   logical (logicals are written as 0/1).
#' @param eta_min Positive scalar, lower bound on the dual variable
#'   \eqn{\eta}{eta}, the multiplier pricing the divergence budget (kept
#'   strictly positive so the perspective function in the dual objective is
#'   well defined).
#' @param lower_limit Scalar; inner (dual) objective values at or below
#'   this threshold are treated as unbounded below (the inner solver's
#'   infeasibility guard).
#' @param psi_tv_eps Positive scalar, Huber smoothing scale for the kinked
#'   total-variation conjugate \eqn{\phi^{*}_{\mathsf{TV}}}{phi_TV^*}. The
#'   smoothed conjugate lies above the exact one, so computed bounds remain
#'   outward-conservative.
#' @param tvac_tau Positive scalar, soft-max temperature for the
#'   log-sum-exp term of the `"TVac"` divergence, that is, total variation
#'   restricted to distributions with \eqn{P \ll P_{*}}{P << P_*}.
#' @param tvmix_tau Positive scalar, soft-max temperature for the
#'   log-sum-exp term of the `"TVmix"` divergence, that is, total variation
#'   intersected with the mixture constraint
#'   \eqn{P \geq \kappa P_{*}}{P >= kappa * P_*}.
#' @param purekl_acap Positive scalar, overflow clamp on the exponent of
#'   the conjugate of the pure Kullback-Leibler entropy
#'   \eqn{\phi_{\mathsf{KL}}(s) = s \log s - s + 1}{phi_KL(s) = s log s - s
#'   + 1}, which increases exponentially in its argument.
#' @param tvmix_kappa `NULL` or a scalar in \eqn{[0,1]}{[0, 1]}: the
#'   contamination weight \eqn{\kappa}{kappa} of the mixture constraint
#'   \eqn{P \geq \kappa P_{*}}{P >= kappa * P_*} used by the `"TVmix"` and
#'   `"TVmixC"` divergences (the perturbed distribution must contain the
#'   baseline as a mixing component with weight \eqn{\kappa}{kappa}).
#'   `NULL` ties \eqn{\kappa}{kappa} to the budget as
#'   \eqn{\kappa = 1 - \delta}{kappa = 1 - delta}, matching Palomba (2026).
#'   An explicit value decouples the two parameters; the reduced `"TVmix"`
#'   program requires \eqn{\kappa \geq 1 - \delta}{kappa >= 1 - delta} (so
#'   that the total-variation constraint is redundant), while `"TVmixC"`
#'   supports any \eqn{\kappa}{kappa} in \eqn{[0,1)}{[0, 1)}.
#'
#' @return A list of class `"tvbounds_control"` with the (validated)
#'   options above.
#'
#' @references
#' Palomba, F. (2026). "Sensitivity Analysis in Population Shares."
#' Working paper.
#'
#' Christensen, T. and B. Connault (2023). "Counterfactual Sensitivity
#' and Robustness." *Econometrica*, 91(1), 263-298.
#'
#' @examples
#' ctrl <- tvbounds_control()
#' ctrl$maxsolves
#'
#' # a faster configuration for exploratory grids
#' tvbounds_control(maxsolves = 3, knitro_options = list(maxit = 200))
#'
#' @seealso [tvbounds_counterfactual()]
#' @export
tvbounds_control <- function(maxsolves = 10,
                             startptrange = 0.01,
                             use_optim = FALSE,
                             time_limit = 60,
                             iterations = 100,
                             outer_iterations = 3,
                             inner_opt = NULL,
                             outer_opt = NULL,
                             knitro_options = list(),
                             eta_min = 1e-120,
                             lower_limit = -10,
                             psi_tv_eps = 1e-4,
                             tvac_tau = 1e-3,
                             tvmix_tau = 1e-3,
                             purekl_acap = 500,
                             tvmix_kappa = NULL) {
  .tvb_check_count(maxsolves, "maxsolves")
  .tvb_check_positive_scalar(startptrange, "startptrange")
  .tvb_check_flag(use_optim, "use_optim")
  .tvb_check_positive_scalar(time_limit, "time_limit")
  .tvb_check_count(iterations, "iterations")
  .tvb_check_count(outer_iterations, "outer_iterations")
  .tvb_check_opt_path(inner_opt, "inner_opt")
  .tvb_check_opt_path(outer_opt, "outer_opt")
  if (!is.list(knitro_options)) {
    stop("`knitro_options` must be a named list.", call. = FALSE)
  }
  if (length(knitro_options) > 0L) {
    nms <- names(knitro_options)
    if (is.null(nms) || any(!nzchar(nms))) {
      stop("every entry of `knitro_options` must be named.", call. = FALSE)
    }
    ok <- vapply(knitro_options, function(v) {
      length(v) == 1L && (is.character(v) || is.numeric(v) || is.logical(v))
    }, logical(1L))
    if (!all(ok)) {
      stop("entries of `knitro_options` must be length-one character, ",
           "numeric, or logical values.", call. = FALSE)
    }
  }
  .tvb_check_positive_scalar(eta_min, "eta_min")
  if (!is.numeric(lower_limit) || length(lower_limit) != 1L ||
      !is.finite(lower_limit)) {
    stop("`lower_limit` must be a finite numeric scalar.", call. = FALSE)
  }
  .tvb_check_positive_scalar(psi_tv_eps, "psi_tv_eps")
  .tvb_check_positive_scalar(tvac_tau, "tvac_tau")
  .tvb_check_positive_scalar(tvmix_tau, "tvmix_tau")
  .tvb_check_positive_scalar(purekl_acap, "purekl_acap")
  if (!is.null(tvmix_kappa)) {
    if (!is.numeric(tvmix_kappa) || length(tvmix_kappa) != 1L ||
        !is.finite(tvmix_kappa) || tvmix_kappa < 0 || tvmix_kappa > 1) {
      stop("`tvmix_kappa` must be NULL or a scalar in [0, 1].",
           call. = FALSE)
    }
  }
  structure(
    list(
      maxsolves        = as.integer(maxsolves),
      startptrange     = as.numeric(startptrange),
      use_optim        = isTRUE(use_optim),
      time_limit       = as.numeric(time_limit),
      iterations       = as.integer(iterations),
      outer_iterations = as.integer(outer_iterations),
      inner_opt        = inner_opt,
      outer_opt        = outer_opt,
      knitro_options   = knitro_options,
      eta_min          = as.numeric(eta_min),
      lower_limit      = as.numeric(lower_limit),
      psi_tv_eps       = as.numeric(psi_tv_eps),
      tvac_tau         = as.numeric(tvac_tau),
      tvmix_tau        = as.numeric(tvmix_tau),
      purekl_acap      = as.numeric(purekl_acap),
      tvmix_kappa      = tvmix_kappa
    ),
    class = "tvbounds_control"
  )
}

# --- small validators -------------------------------------------------

#' Validate a positive integer-like scalar
#' @keywords internal
#' @noRd
.tvb_check_count <- function(x, name) {
  if (!is.numeric(x) || length(x) != 1L || !is.finite(x) ||
      x < 1 || x != as.integer(x)) {
    stop(sprintf("`%s` must be a positive integer.", name), call. = FALSE)
  }
  invisible(TRUE)
}

#' Validate a strictly positive finite scalar
#' @keywords internal
#' @noRd
.tvb_check_positive_scalar <- function(x, name) {
  if (!is.numeric(x) || length(x) != 1L || !is.finite(x) || x <= 0) {
    stop(sprintf("`%s` must be a positive finite scalar.", name),
         call. = FALSE)
  }
  invisible(TRUE)
}

#' Validate a length-one logical
#' @keywords internal
#' @noRd
.tvb_check_flag <- function(x, name) {
  if (!is.logical(x) || length(x) != 1L || is.na(x)) {
    stop(sprintf("`%s` must be TRUE or FALSE.", name), call. = FALSE)
  }
  invisible(TRUE)
}

#' Validate an optional KNITRO option-file path
#' @keywords internal
#' @noRd
.tvb_check_opt_path <- function(x, name) {
  if (is.null(x)) return(invisible(TRUE))
  if (!is.character(x) || length(x) != 1L || !nzchar(x)) {
    stop(sprintf("`%s` must be NULL or a single file path.", name),
         call. = FALSE)
  }
  if (!file.exists(x)) {
    stop(sprintf("`%s` points to a file that does not exist: %s", name, x),
         call. = FALSE)
  }
  invisible(TRUE)
}

#' Merge user overrides into a KNITRO option file
#'
#' Reads `base`, replaces the value of every option named in `overrides`
#' (appending options not already present), and writes the merged file
#' to [tempdir()]. The base file is never modified.
#'
#' @param base Path to an existing KNITRO `.opt` file.
#' @param overrides Named list of length-one character/numeric/logical
#'   values (logicals are written as 0/1).
#' @return The path of the merged temporary file.
#' @keywords internal
#' @noRd
.tvb_merge_opt_file <- function(base, overrides) {
  stopifnot(is.character(base), length(base) == 1L, file.exists(base),
            is.list(overrides), length(overrides) > 0L)
  lines <- readLines(base, warn = FALSE)
  for (nm in names(overrides)) {
    val <- overrides[[nm]]
    if (is.logical(val)) val <- as.integer(val)
    valstr <- as.character(val)
    hit <- grepl(paste0("^\\s*", nm, "(\\s|$)"), lines)
    repl <- paste(nm, valstr)
    if (any(hit)) {
      lines[hit] <- repl
    } else {
      lines <- c(lines, repl)
    }
  }
  out <- tempfile(pattern = "tvbounds_", fileext = ".opt")
  writeLines(lines, out)
  out
}

#' Resolve the inner/outer KNITRO option files for one call
#'
#' Applies the shipped defaults when the control list does not name its
#' own files, and merges `knitro_options` overrides into temporary
#' copies when present.
#'
#' @param control A `"tvbounds_control"` list.
#' @return A list with elements `inner` and `outer` (file paths).
#' @keywords internal
#' @noRd
.tvb_resolve_opt <- function(control) {
  inner <- control$inner_opt %||%
    system.file("julia", "opt", "inner.opt", package = "tvbounds")
  outer <- control$outer_opt %||%
    system.file("julia", "opt", "outer.opt", package = "tvbounds")
  if (!nzchar(inner) || !file.exists(inner)) {
    stop("could not locate the inner KNITRO option file; ",
         "supply `inner_opt` in tvbounds_control().", call. = FALSE)
  }
  if (!nzchar(outer) || !file.exists(outer)) {
    stop("could not locate the outer KNITRO option file; ",
         "supply `outer_opt` in tvbounds_control().", call. = FALSE)
  }
  if (length(control$knitro_options) > 0L) {
    inner <- .tvb_merge_opt_file(inner, control$knitro_options)
    outer <- .tvb_merge_opt_file(outer, control$knitro_options)
  }
  list(inner = inner, outer = outer)
}
